server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/** /menus/**
        - id: Delivery
          uri: http://localhost:8082
          predicates:
            - Path=/deliveries/** 
        - id: management
          uri: http://localhost:8083
          predicates:
            - Path= /statusChecks/**
        - id: Payment
          uri: http://localhost:8084
          predicates:
            - Path=/payments/** 
        - id: Store
          uri: http://localhost:8085
          predicates:
            - Path=/menus/** 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://order:8080
          predicates:
            - Path=/orders/** /menus/**
        - id: Delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveries/** 
        - id: management
          uri: http://management:8080
          predicates:
            - Path= /statusChecks/**
        - id: Payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/** 
        - id: Store
          uri: http://store:8080
          predicates:
            - Path=/menus/** 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
